# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(major).$(minor).$(Date:yyMM).$(Rev:r)

resources:
  repositories:
  - repository: group-membership-management
    type: git
    name: <ADO-PROJECT>/<ADO-GMM-PUBLIC-REPOSITORY>
    ref: refs/tags/<TAG>

trigger:
- develop
- master
- main
- users/*

pool:
  vmImage: "windows-latest"

variables:
  "major": '2'
  "minor": '0'
  "BuildConfiguration": 'debug'
  "SolutionAbbreviation": 'gmm'
  disable.coverage.autogenerate: 'true'
  "buildRelease": ${{  in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/main') }}
  tools.ref: $[ resources.repositories['group-membership-management'].ref ]

stages:

- template: build-services.yml@group-membership-management
  parameters:
    repoToCheckout: group-membership-management
    checkoutPath: '$(Build.BuildNumber)'
    buildRelease: ${{variables.buildRelease}}

- template: yaml/build-functionapps.yml@group-membership-management
  parameters:
    dependsOn: Build_Common
    condition: succeeded('Build_Common')
    repoToCheckout: group-membership-management
    checkoutPath: '$(Build.BuildNumber)'
    buildRelease: ${{variables.buildRelease}}
    functionApps:
    - function:
       name: 'NonProdService'
       coverageThreshold: 100
    - function:
       name: 'JobTrigger'
       coverageThreshold: 89
    - function:
       name: 'GraphUpdater'
       coverageThreshold: 74
    - function:
       name: 'GroupMembershipObtainer'
       coverageThreshold: 89
    - function:
       name: 'TeamsChannel'
       coverageThreshold: 72
    - function:
       name: 'AzureMaintenance'
       coverageThreshold: 95
    - function:
       name: 'AzureUserReader'
       coverageThreshold: 68
    - function:
       name: 'JobScheduler'
       coverageThreshold: 48
    - function:
       name: 'MembershipAggregator'
       coverageThreshold: 85
    - function:
       name: 'Notifier'
       coverageThreshold: 75
    - function:
       name: 'GroupOwnershipObtainer'
       coverageThreshold: 80

- template: yaml/copy-parameter-files.yml
  parameters:
    buildRelease: ${{variables.buildRelease}}
    functionApps:
    - name: 'NonProdService'
    - name: 'JobTrigger'
    - name: 'GraphUpdater'
    - name: 'GroupMembershipObtainer'
    - name: 'TeamsChannel'
    - name: 'AzureUserReader'
    - name: 'JobScheduler'
    - name: 'MembershipAggregator'
    - name: 'AzureMaintenance'
    - name: 'Notifier'
    - name: 'GroupOwnershipObtainer'

- template: yaml/copy-deploy-webapp.yml
  parameters:
    alias: ''
    solutionAbbreviation: '$(SolutionAbbreviation)'
    environmentAbbreviation: 'env'
    tenantId: $(tenantId)
    subscriptionId: $(subscriptionId_nonprod)
    keyVaultReaders: $(keyVaultReaders_nonprod)
    location: $(location)
    serviceConnection: '$(SolutionAbbreviation)-serviceconnection-env'
    buildRelease: ${{variables.buildRelease}}
    stageName: 'NonProd_webapp_env'
    condition: |
      and(
        succeeded('Build_WebApp'),
        eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      )

- template: yaml/deploy-pipeline.yml
  parameters:
    solutionAbbreviation: '$(SolutionAbbreviation)'
    environmentAbbreviation: 'env'
    tenantId: $(tenantId)
    subscriptionName: $(subscriptionName_nonprod)
    subscriptionId: $(subscriptionId_nonprod)
    keyVaultReaders: $(keyVaultReaders_nonprod)
    location: $(location)
    serviceConnection: '$(SolutionAbbreviation)-serviceconnection-env'
    dependsOn:
    - Build_Common
    - Build_CopyParameters
    stageName: 'NonProd_env'
    functionApps:
    - function:
       name: 'NonProdService'
    - function:
       name: 'GraphUpdater'
    - function:
       name: 'MembershipAggregator'
       dependsOn:
       - 'GraphUpdater'
    - function:
       name: 'AzureUserReader'
    - function:
       name: 'GroupMembershipObtainer'
       dependsOn:
       - 'MembershipAggregator'
    - function:
       name: 'GroupOwnershipObtainer'
       dependsOn:
       - 'MembershipAggregator'
    - function:
       name: 'TeamsChannel'
       dependsOn:
       - 'MembershipAggregator'
    - function:
       name: 'AzureMaintenance'
    - function:
       name: 'JobTrigger'
       dependsOn:
       - 'MembershipAggregator'
    - function:
       name: 'Notifier'
    deployJobScheduler: true
    condition: |
      and(
        succeeded('Build_Common'),
        succeeded('Build_CopyParameters'),
        eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
        in(variables['Build.Reason'], 'IndividualCI', 'Manual')
      )

